[package]
name = "clef"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.66", features = ["backtrace"] }
camino = "1.1.1"
dirs = "4.0.0"
flume = { version = "0.10.14" }
itertools = "0.10.5"
log = { version = "0.4", features = ["release_max_level_info"] }
parking_lot = "0.12.1"
pretty_env_logger = "0.4"
symphonia = { version = "0.5.1", features = ["mp3"] }
thiserror = "1.0.37"
walkdir = "2.3.2"

[dependencies.iced]
git = "https://github.com/iced-rs/iced"
version = "0.5"
features = ["svg", "image", "debug"]

[dependencies.iced_native]
git = "https://github.com/iced-rs/iced"
version = "0.6"

[dependencies.image_rs]
package = "image"
version = "0.24"

[target.'cfg(target_os = "linux")'.dependencies]
libpulse-binding = "2.5.0"
libpulse-simple-binding = "2.5.0"

[target.'cfg(not(target_os = "linux"))'.dependencies]
cpal = "0.13.3"
rb = "0.3.2"

[dev-dependencies]
mockall = "0.11.3"

# compile all dependencies in release mode
[profile.dev.package."*"]
opt-level = 3
