[package]
name = "clef"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.66", features = ["backtrace"] }
camino = "1.1.1"
diesel_migrations = { version = "2.0.0", features = ["sqlite"] }
directories = "4.0.1"
flume = { version = "0.10.14" }
log = { version = "0.4", features = ["release_max_level_info"] }
parking_lot = "0.12.1"
pretty_env_logger = "0.4"
r2d2 = "0.8.10"
symphonia = { version = "0.5.1", features = ["mp3"] }
thiserror = "1.0.37"
libsqlite3-sys = { version = "0.25.2", features = ["bundled"] }

iced_graphics = "0.8.0"
iced_style = "0.8.0"

[dependencies.souvlaki]
git = "https://github.com/Giesch/souvlaki"
branch = "main"

[dependencies.iced]
version = "0.9"
features = ["svg", "image", "debug"]

[dependencies.iced_native]
version = "0.10.1"

[dependencies.image_rs]
package = "image"
version = "0.24"

[dependencies.diesel]
version = "2.0.2"
features = ["sqlite", "r2d2", "returning_clauses_for_sqlite_3_35"]

[target.'cfg(target_os = "linux")'.dependencies]
libpulse-binding = "2.5.0"
libpulse-simple-binding = "2.5.0"

[target.'cfg(not(target_os = "linux"))'.dependencies]
cpal = "0.13.3"
rb = "0.3.2"

[dev-dependencies]
mockall = "0.11.3"

# compile all dependencies in release mode
[profile.dev.package."*"]
opt-level = 3
