* Now
- [-] choose an option for dealing with image perf
  - [X] first, see if cloning bytes is the problem
    from_pixels doesn't allow avoiding this
  - [X] try keeping handles in app state
    Image::new still has to take ownership
  - [ ] is it possible to use an overlay & custom style?
    ie always draw a transparent button over the number
    should the content or the hoverable have the overlay?
    can this be simplified by making a widget for just this case?
      ie the cutom widget is for track numbers and play buttons
  - [ ] then, pick one:
    - remove images from the app for now
    - make an infinite list widget https://github.com/iced-rs/iced/issues/160
    - try to address cache issue https://github.com/iced-rs/iced/issues/549

* Next
- [ ] use the new custom theme options
  - [ ] transparent background play button for song list
  - [ ] transparent background forward/back buttons
  - [ ] make the play button unique as well?

- [ ] make a custom Effect type wrapping Command and ToAudio
  also make non-channel stuff a sub-struct?

- [ ] add a config dir
  consider switching to 'directories' crate from 'dirs'

- [ ] start using sqlite for decoded data
  remove the unwraps/expects from ui::data
  replace the weird joins in ui::startup
  match album covers to albums in a less dumb way
  change startup process to be more incremental
    ie, can happen in the background while app is interactive,
    and start where it left off if app is killed

- [ ] in player, if audio output is present,
  then spec and duration should still be validated

- [ ] in ui, current_song and progress should be in one optional

- [ ] cache the converted rgba images in config dir
  also resize to thumbnails? for currently playing

- [ ] add song durations to view
  - [ ] for currently playing song
  - [ ] in the album song list

- [ ] make a custom slider / player progress widget
  style it differently
  no mouse interaction when disabled
  change mouse interaction consistently on release

- [ ] thumbnail album art for currently playing song
  or next to songs in a non-album view

- [ ] handle metadata correctly in the audio thread
  https://github.com/pdeljanov/Symphonia/blob/master/GETTING_STARTED.md#consuming-metadata
  was symphonia-play doing that in the print helpers?

- [ ] switch to tracing from env-logger
  look into whether it plays nice with iced exector

- [ ] read symphonia docs thoroughly
- [ ] read iced examples thoroughly

- [ ] handle graceful shutdown on the audio thread
  need a typed return from the run method?
  or a way for the ui to join audio instead of disconnecting

- [ ] custom app theme with a transparent background secondary button
  - [ ] copy dark theme into app (delegate to it somehow?)
  - [ ] change secondary button to have transparent background & white/gray stroke
  - [ ] use secondary for hovered song play button

- [ ] make hover state update immediately
  could have both elements ready always, and draw based on mouse position
    but this requires a way to keep laying out the invisible element
  maybe use an overlay?
  see if getting to smaller scrollables helps

* Someday
- [ ] sqlite setup
  - [ ] load a nice startup ui quickly
  - [ ] last played song
  - [ ] music directory index
  - [ ] tags
  - [ ] re-evaluate the expect/unwraps taking song ids
  - [ ] figure out how the ui and audio threads should share songs
    id/path/somthing else

- [ ] playlists
- [ ] current queue (treat like another kind of playlist)
- [ ] other views

- [ ] handle missing time data on track info
  currently it just logs and uses zero
  should transition to an error state at the beginning
  ie have an Option<TrackInfo> with guaranteed fields
  instead of a TrackInfo with two optional fields
  does that mean refusing to play the song at all, though? need the id

- [ ] integration tests
- [ ] restart audio thread after a crash

- [ ] help improve iced's image handling
- [ ] Address scrolling lag when necessary

- [ ] keyboard support
  - [ ] space for play/pause
  - [ ] support media keys
  - [ ] tab navigation

- [ ] drag and drop import

- [ ] non-latin text (use cosmic's stuff early?)
  https://github.com/iced-rs/iced/issues/1454

- [ ] select the music directory with a menu/modal, and cache it
- [ ] select the config directory based on platform

- [ ] add a subtle play button to album art
